### PR TITLE
Fix CSV parsing

### PR DESCRIPTION
**Pull request by peterableda**

### CODE REVIEW

**Comment by peterableda** [comment]
You need to rescue with `MalformedCSVError`. If there is a line with a badly formatted row the whole processing brakes.

**Comment by rgabo** [comment]
@peterableda I have fixed the CSV parsing issue last night and refactored the converter to be easier to read. There are still two tests failing because somehow the `AvroReader` does not work as its supposed to.

**Comment by peterableda** [comment]
You are parsing every row and writing the parsed data to the bad rows upon errors. This way the bad rows won't contain the **original** data.

**Comment by peterableda** [comment]
I think you need to update the travis settings of the project. We are open source now! :+1:

**Comment by rgabo** [comment]
@peterableda parsing by row is not an option. `CSV` will parse perfectly valid multi-line CSV quote fields. The only option with malformed CSVs is to abort because the CSV parser will not recover. Check `MalformedCSVError` in the official documentation: http://ruby-doc.org/stdlib-2.1.0/libdoc/csv/rdoc/CSV.html#method-c-new

It is only raised if a field is unterminated. This can only happen if you actually break the CSV and try to parse it line by line.

I agree that it should be handled gracefully with a message.

**Comment by peterableda** [comment]
I don't know what happened yesterday. The 1.0.0 worked for me today too. So the quoted fields don't do any harm. 

It's not too hard to break a line so we need to handle this case.

**Comment by peterableda** [comment]
@rgabo It's done

**Comment by rgabo** [comment]
@peterableda good stuff. Instead of << "...\n", you should  use IO#puts which will take care of that on every platform.

**Pull request merged**
